server:
  port:  8080

spring:
  application:
    name: oauth2-with-pkce

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${FRONTEND_URL}/auth/callback 
            scope: openid, email, profile
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 3600000 # 1 hour in milliseconds (short-lived access token)

